return {
	Author = "Exponetia",
	Description = "当太吾村庄缺乏资源，而村民却拥有足够的资源时，太吾与村民之间可以建立一种合作关系。 \n通过购买/交换村民的物资，实现资源共享。 \n双赢才是真的赢(仁善。 \n太吾每月将用溢出的资源，威望，金钱跟村民交易。 \n优先级是 : 溢出资源 > 威望 > 金钱。 \n由于不想管边缘作用, 当资源超过仓库的百分之八十，我就当作溢出来处理。 \n购买力大概是 : \n1资源=4金钱 \n2资源=1威望。 \n这是我逆炼C#两天时间搞出来的, 要是有bug或者其他问题欢迎留言。 \n在此非常感谢宵夜大佬的视频教程以及AmekiKyou的开源模组[月末资源再分配&素材进货]。 \n等代码简洁了不少后，我也会开源的 (刚正) ",
	Version = "2",
	DefaultSettings = {
		[1] = {
			SettingType = "Toggle",
			Key = "buyResources",
			DefaultValue = true,
			Description = "当开启时，太吾每月结算前都会跟村民交换以及购买资源",
			DisplayName = "购买资源",
		},
		[2] = {
			SettingType = "Slider",
			Key = "TaiwuBudgetRate",
			StepSize = 1,
			DefaultValue = 10,
			Description = "每个月太吾打算花费多少当前金钱的比例",
			DisplayName = "金钱预算",
			MaxValue = 100,
			MinValue = 0,
		},
		[3] = {
			SettingType = "Slider",
			Key = "TaiwuRenownRate",
			StepSize = 1,
			DefaultValue = 10,
			Description = "每个月太吾打算花费多少当前威望的比例",
			DisplayName = "威望预算",
			MaxValue = 100,
			MinValue = 0,
		},
		[4] = {
			SettingType = "Slider",
			Key = "minimumPlants",
			StepSize = 100,
			DefaultValue = 200,
			Description = "低于这个数值，村民不愿意跟太吾用草药交易",
			DisplayName = "村民最低草药",
			MaxValue = 1000,
			MinValue = 0,
		},
		[5] = {
			SettingType = "Toggle",
			Key = "DebugInfo",
			DefaultValue = false,
			Description = "开启后会在游戏Logs文件夹下最新的GameData里写入具体的交易信息",
			DisplayName = "debug信息",
		},
	},
	Source = 1,
	Title = "平衡的资源共享",
	WorkshopCover = "Cover.png",
	BackendPlugins = {
		[1] = "BuyVillagersResources.dll",
	},
	Cover = "Cover.png",
	FileId = 3125189480,
	GameVersion = "0.0.67.63",
}
