return {
	Author = "Exponetia",
	Description = "在太吾村人口不断增长的后期，居住条件供不应求。 \n由于无法提供足够居住空间，一些村民的心情逐渐变差，甚至有的入魔，对太吾产生了极大的敌意。 \n太吾村本就生活清苦，对无家可归之人更是如此。 \n有些人可能认为在附近的大城市做乞丐比留在太吾村更好。\n此时，筛选出适合留下的村民变得至关重要，他们将为太吾对抗相枢出一份力量。这是一项正义之举。   \n\n因此，这个模组允许自定义村民被自愿离开的条件，不符合保留条件的村民每月底将被驱逐。 \n符合任意保留条件的村民将不会被驱逐。 \n由于村民会记得在村子里经历的艰辛时光，他们对太吾的好感也可能下降，甚至回来寻仇。 \n太吾需要承担这份因果。(刚正）\n基于坊主朴素的道德感，同道以及孩童不会离开 (仁善)。 \n使用此mod需要三思，不要一不小心就把高质量人才给驱逐咯 (叛逆）",
	Version = "2",
	DefaultSettings = {
		[1] = {
			SettingType = "Toggle",
			Key = "doExpel",
			DefaultValue = false,
			Description = "当开启时，每月都会筛选村民符合居住条件的村民",
			DisplayName = "驱逐村民",
		},
		[2] = {
			SettingType = "Slider",
			Key = "maximalAge",
			StepSize = 1,
			DefaultValue = 15,
			Description = "低于这个数值，村民不会离开。\n15代表关闭此选项，也就是说全年龄都有可能离开",
			DisplayName = "年龄",
			MaxValue = 120,
			MinValue = 15,
		},
		[3] = {
			SettingType = "Slider",
			Key = "minimalCharm",
			StepSize = 10,
			DefaultValue = -1,
			Description = "高于这个数值，村民不会离开。\n注意该数值为基础值没有经过毛发和年龄的减益，以及衣服的加成。 \n-1代表关闭此选项，也就是说全魅力都有可能离开",
			DisplayName = "基础魅力",
			MaxValue = 800,
			MinValue = -1,
		},
		[4] = {
			SettingType = "Slider",
			Key = "forbiddenBehavior",
			StepSize = 1,
			DefaultValue = -1,
			Description = "保留不是该立场的村民。 \n0-4分别是刚正，仁善，中庸，叛逆，唯我。 \n-1代表关闭此选项，也就是说: \n全立场都可能被驱逐 ",
			DisplayName = "立场",
			MaxValue = 4,
			MinValue = -1,
		},
		[5] = {
			SettingType = "Slider",
			Key = "minimalLifeSkillQualification",
			StepSize = 5,
			DefaultValue = -1,
			Description = "高于这个数值，村民不会离开。\n该数值为基础值，没有经过特性，祠堂的加成 \n-1代表关闭此选项，也就是说: \n无论村民的最高技艺资质有多少，仍然有可能被驱逐",
			DisplayName = "最高技艺资质",
			MaxValue = 120,
			MinValue = -1,
		},
		[6] = {
			SettingType = "Slider",
			Key = "minimalLifeSkillAttainment",
			StepSize = 10,
			DefaultValue = -1,
			Description = "高于这个数值，村民不会离开。\n该数值为基础值，没有经过建筑等的加成 \n-1代表关闭此选项，也就是说: \n无论村民的最高技艺造诣有多少，仍然有可能被驱逐",
			DisplayName = "最高技艺造诣",
			MaxValue = 500,
			MinValue = -1,
		},
		[7] = {
			SettingType = "Slider",
			Key = "minimalCombatSkillQualification",
			StepSize = 5,
			DefaultValue = -1,
			Description = "高于这个数值，村民不会离开。\n该数值为基础值，没有经过特性，祠堂的加成。 \n-1代表关闭此选项，也就是说: \n无论村民的最高武学资质有多少，仍然有可能被驱逐",
			DisplayName = "最高功法资质",
			MaxValue = 120,
			MinValue = -1,
		},
		[8] = {
			SettingType = "Slider",
			Key = "minimalCombatSkillAttainment",
			StepSize = 10,
			DefaultValue = -1,
			Description = "高于这个数值，村民不会离开。\n该数值为基础值，没有经过建筑等的加成。 \n-1代表关闭此选项，也就是说: \n无论村民的最高武学资质有多少，仍然有可能被驱逐",
			DisplayName = "最高功法造诣",
			MaxValue = 500,
			MinValue = -1,
		},
		[9] = {
			SettingType = "Toggle",
			Key = "DebugInfo",
			DefaultValue = false,
			Description = "开启后会在游戏Logs文件夹下最新的GameData里写入具体的筛选信息",
			DisplayName = "debug信息",
		},
	},
	Source = 1,
	Title = "驱逐劣质村民",
	BackendPlugins = {
		[1] = "ExpelTheLower.dll",
	},
	Cover = "Cover.png",
	FileId = 3132133029,
	GameVersion = "0.0.67.63",
}
